### ISSUE TITLE
Issue with composer

### ISSUE THREAD

**Issue by ooyo** [akaramires/laravel-googleforms#2]
i'm having installation issue with composer. I'm using laravel 5.6

> [InvalidArgumentException]                                                                           
> Could not find a matching version of package akaramires/laravel-googleforms. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by t-prod** [comment]
I confirm it's not compatible with Laravel 5.5.X. Could you upgrade your package please ?

![2018-05-24_12-58-47](https://user-images.githubusercontent.com/1824638/40481634-4c6efed2-5f52-11e8-8535-81ca17ee6f28.jpg)

Thanks

**Comment by archisss** [comment]
isn't is compatible with laravel 5.8  :(

<img width="806" alt="Captura de pantalla 2019-06-19 a la(s) 11 56 21" src="https://user-images.githubusercontent.com/517183/59784986-507c2980-9289-11e9-81a2-c796e5dca3a9.png">

**Comment by akaramires** [comment]
Fixed
